# Generated by Django 2.2.4 on 2019-08-19 18:41

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190813_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='agenda',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
