# Generated by Django 2.2.9 on 2020-01-19 08:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('events', '0005_auto_20191107_1140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventPage',
            new_name='Event',
        ),
    ]
