# Generated by Django 2.2.4 on 2019-11-08 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20191104_0633'),
        ('events', '0005_auto_20191107_1140'),
    ]

    operations = [
    ]
