# Generated by Django 2.2.7 on 2019-11-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_merge_20191108_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='attended',
            field=models.IntegerField(blank=True, help_text='Please enter the number of people that attended, or leave blank', null=True),
        ),
    ]
