# Generated by Django 2.2.7 on 2020-01-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20191114_2100'),
        ('events', '0006_auto_20200119_0854'),
    ]

    operations = [
    ]
