# Generated by Django 3.0.8 on 2020-07-01 20:38

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200701_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('jumbotron', wagtail.core.blocks.RawHTMLBlock())]),
        ),
    ]
