# Generated by Django 2.2.9 on 2020-01-16 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20191107_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='page',
            new_name='menu',
        ),
    ]
