# Generated by Django 2.2.4 on 2019-11-08 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20191107_1140'),
        ('menus', '0002_auto_20191014_2118'),
    ]

    operations = [
    ]
