# Generated by Django 2.2.7 on 2020-01-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_auto_20200116_2210'),
        ('menus', '0003_merge_20191108_2107'),
    ]

    operations = [
    ]
